spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: db7a381de74b0bb195f1fe2041a86a2b
            client-secret: QeryEfCeyyo2WkwtTR6K6Tt2DLPAOAAT
            redirect-uri: http://localhost:8180/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
          naver:
            client-id: SLmJghQfwwtZynfJ4A9n
            client-secret: kmmn7y6GBL
            redirect-uri: http://localhost:8180/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          google:
            client-id: 766866594883-emgb36g5ufb71casjt6gj8p7bhptf6sv.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  profiles:
    default: local # 기본 환경을 dev로

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB