--SpringBoot 서버가 새로 시작할 때 이 파일의 쿼리들이 자동으로 실행됨

INSERT INTO USERS (USER_INDEX, USERID, PASSWORD, USERNAME, NICKNAME, ADDRESS, PHONE, ACTIVATED) VALUES (1, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', 'admin', 'admin', '010', 1);
INSERT INTO USERS (USER_INDEX, USERID, PASSWORD, USERNAME, NICKNAME, ADDRESS, PHONE, ACTIVATED) VALUES (2, 'lhj', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'lhj', '경기도', 'gidwns', '010', 1);

INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_USER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_INDEX, AUTHORITY_NAME) values (1, 'ROLE_USER');
INSERT INTO USER_AUTHORITY (USER_INDEX, AUTHORITY_NAME) values (1, 'ROLE_ADMIN');
INSERT INTO USER_AUTHORITY (USER_INDEX, AUTHORITY_NAME) values (2, 'ROLE_USER');
